export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string; // HTML string or plain text for now
  author: string;
  date: string;
  image: string;
  category: string;
  category_slug?: string; // resolved via join against blog_categories.name, used for /category/{slug} links
  tags?: string[];
  tagIds?: number[];
  tag_slugs?: string[]; // parallel array to `tags`, used for /tag/{slug} links
  meta_title?: string;
  meta_keywords?: string;
  meta_des?: string;
}

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "understanding-ayurvedic-diet-for-kidney-health",
    title: "Understanding the Ayurvedic Diet for Kidney Health",
    excerpt: "Discover the ancient secrets of Ayurveda to naturally detoxify your kidneys and improve overall renal health through mindful eating.",
    content: `
      <p>Your diet plays a pivotal role in maintaining the health of your kidneys. According to Ayurveda, improper dietary habits (Apathya) lead to the accumulation of toxins (Ama), which slowly impair the kidney's filtration system.</p>
      
      <h3>The Role of Agni (Digestive Fire)</h3>
      <p>In Ayurveda, a strong digestive fire (Agni) is essential. When Agni is weak, toxins build up in the body. For kidney patients, it is crucial to eat foods that are light, easy to digest, and pacifying to the Vata and Pitta doshas.</p>

      <h3>Foods to Include</h3>
      <ul>
        <li><strong>Fresh Fruits:</strong> Apples, papayas, and berries are generally safe and rich in antioxidants.</li>
        <li><strong>Vegetables:</strong> Bottle gourd (Lauki), pointed gourd (Parwal), and ridge gourd (Tori) are highly recommended.</li>
        <li><strong>Grains:</strong> Quinoa, barley, and old rice are easy on the kidneys.</li>
      </ul>

      <h3>Foods to Avoid</h3>
      <p>Processed foods, excessively salty foods, red meat, and heavy dairy products put an unnecessary burden on the kidneys and should be strictly avoided.</p>
      
      <p><em>Always consult with an Ayurvedic physician before making drastic changes to your diet, especially if you are dealing with Chronic Kidney Disease (CKD).</em></p>
    `,
    author: "Dr. Puneet Dhawan",
    date: "October 12, 2023",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    category: "Diet & Nutrition"
  },
  {
    id: "2",
    slug: "panchakarma-therapy-for-detoxification",
    title: "Panchakarma Therapy: The Ultimate Detox",
    excerpt: "Learn how Panchakarma therapy cleanses the body of deep-rooted toxins and helps rejuvenate the organs naturally.",
    content: `
      <p>Panchakarma is the cornerstone of Ayurvedic detoxification. It consists of five (Pancha) actions (Karma) that eliminate toxic elements from the body.</p>
      
      <h3>Why is Detoxification Important?</h3>
      <p>Over time, environmental pollutants, poor diet, and stress cause toxins to accumulate in the tissues. This accumulation is the root cause of many chronic diseases, including renal failure.</p>
      
      <h3>The Therapies</h3>
      <ul>
        <li><strong>Vamana:</strong> Therapeutic vomiting to remove excess Kapha.</li>
        <li><strong>Virechana:</strong> Purgation therapy to eliminate Pitta toxins.</li>
        <li><strong>Basti:</strong> Medicated enema, highly effective for Vata disorders and kidney health.</li>
      </ul>
      
      <p>At Karma Ayurveda, we tailor Panchakarma treatments to the individual's constitution and specific health conditions, ensuring a safe and effective healing journey.</p>
    `,
    author: "Dr. Aarti Sharma",
    date: "September 28, 2023",
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=800&q=80",
    category: "Therapies"
  },
  {
    id: "3",
    slug: "managing-creatinine-levels-naturally",
    title: "How to Manage High Creatinine Levels Naturally",
    excerpt: "High creatinine is a common indicator of poor kidney function. Here are natural, Ayurvedic ways to manage and lower it.",
    content: `
      <p>Creatinine is a waste product generated by muscle metabolism. Healthy kidneys filter it out, but when kidney function declines, creatinine levels rise.</p>
      
      <h3>Hydration is Key</h3>
      <p>While fluid intake might need to be monitored in severe CKD, drinking adequate water is generally essential to help the kidneys flush out toxins.</p>

      <h3>Herbal Remedies</h3>
      <p>Ayurveda offers potent herbs like <strong>Punarnava</strong>, <strong>Gokshura</strong>, and <strong>Varuna</strong>, which have diuretic properties and help rejuvenate renal tissues.</p>

      <h3>Lifestyle Modifications</h3>
      <ul>
        <li>Avoid intense, strenuous exercise which can increase creatinine production.</li>
        <li>Manage stress through Yoga and Pranayama.</li>
        <li>Ensure adequate sleep.</li>
      </ul>
    `,
    author: "Dr. Puneet Dhawan",
    date: "November 05, 2023",
    image: "https://images.unsplash.com/photo-1576091160550-2173ff9e5ee5?auto=format&fit=crop&w=800&q=80",
    category: "Kidney Health"
  },
  {
    id: "4",
    slug: "yoga-poses-for-healthy-kidneys",
    title: "5 Yoga Poses for Healthy Kidneys",
    excerpt: "Incorporate these simple yet effective yoga asanas into your daily routine to stimulate kidney function and reduce stress.",
    content: `
      <p>Yoga is a holistic practice that benefits both the mind and body. Certain asanas specifically target the abdominal region, stimulating the kidneys and improving blood circulation.</p>
      
      <h3>Top Asanas for Renal Health</h3>
      <ol>
        <li><strong>Bhujangasana (Cobra Pose):</strong> Stretches the abdomen and stimulates the abdominal organs.</li>
        <li><strong>Paschimottanasana (Seated Forward Bend):</strong> Compresses the abdominal area, giving a massage-like effect to the kidneys.</li>
        <li><strong>Ardha Matsyendrasana (Half Lord of the Fishes Pose):</strong> A twisting pose that helps detoxify the internal organs.</li>
      </ol>
      
      <p>Always practice yoga under the guidance of a certified instructor, especially if you have pre-existing health conditions.</p>
    `,
    author: "Dr. Aarti Sharma",
    date: "August 18, 2023",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
    category: "Lifestyle"
  }
];

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug);
}
